### ISSUE TITLE
Extract list of files to optimize into a config

### ISSUE THREAD

**Issue by nasyrov** [appstract/laravel-opcache#48]
Hi there,

Thanks for the awesome package!

I was wondering if you could extract the following into a config so If I would like to modify it I could simply publish it.

``` php
        // Get files in these paths
        $files = File::allFiles([
            base_path('app'),
            base_path('bootstrap'),
            base_path('public'),
            base_path('resources/lang'),
            base_path('routes'),
            base_path('storage/framework/views'),
            base_path('vendor/appstract'),
            base_path('vendor/composer'),
            base_path('vendor/laravel/framework'),
        ]);
```

The reason being I could manually define the packages that have to be cached. For example in my case I wrote the app using Lumen and I would like to include the framework itself `base_path('vendor/lumen-framework')`.

Cheers,
Evgenii

**Comment by 4sh3** [comment]
Hi, what is exactly the utility of this package and when should I use it?

**Comment by ovanschie** [comment]
@nasyrov 

Glad you like it! Will consider your proposal, but not high priority right now because the files will be cached regardlessly of the optimize command; the impact is very minimal. 

If you want, you can always open an PR of course :)

@4sh3 

You can read the article I wrote on Medium, if you have further questions you can contact us (find the contact details on our Github page)

The article:
https://medium.com/appstract/make-your-laravel-app-fly-with-php-opcache-9948db2a5f93

**Comment by ovanschie** [comment]
This is now possible in the 1.3 release :)

**Comment by nasyrov** [comment]
@ovanschie thanks!
